### ISSUE TITLE
Save Search Button doesn't track url

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/pathways#178]
### Pre-requisites

- [x] I have pulled the latest changes from the Origin
- [x] I have made sure to update my environment by running `npm install` on my terminal
- [x] I have tried to identify the source of the problem before submitting a report

### Description of the Bug

The Save search button stays grey when we click a previously saved search. If we search the same terms through the `TextSearch` component then the save search button lights up pink

### What should happen instead

The `SavedSearch.tsx` component should always turn pink if we navigate to a search that has been previously saved - whether we do it by searching the same terms again or by clicking the saved searchers link 

### Assignment

This issue is free for anyone to take

**Comment by camelPhonso** [comment]
> I am seeing it pink when I load a previous saved state

🤔 mine seems to only be breaking when I click a previously saved search that has more than one search term. So `teacher` works fine but `developer, teacher` breaks.

Can you check if doing that breaks it for you?

**Comment by ShaughnAnderson94** [comment]
![OLD V NEW](https://github.com/user-attachments/assets/57c8f003-b102-426f-99f1-8b899eb256a5)
Ok yeah you can see here the two new ones from the current version of dev work its just older ones saved a while ago that dont. Should not be an issue but maybe we should clear out our local storage @camelPhonso

**Comment by camelPhonso** [comment]
Found out what edge case triggers this.

Any search that includes spaces in the query leads to this behaviour. All other cases work fine
