### ISSUE TITLE
 Populate Sector Selection Dropdown

### ISSUE THREAD

**Issue by mb556** [enBloc-org/pathways#43]
### Expected Behaviour

The dropdown should be populated with sector options. Use hardcoded sectors or fetch from an API.

### Current Behaviour

the dropdown is empty

**Comment by PL1106** [comment]
To do this I will fetch data using API calls or database queries then make it understandable and format it

**Comment by mb556** [comment]
Hi Alphonso, sorry I’m running slightly behind schedule today

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ShaughnAnderson94** [comment]
Hey where are you are you still running behind schedule what is happening

**Comment by mb556** [comment]
Hi, I fell ill today and decided to give it a rest. Ill be back in tomorrow

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
