### ISSUE TITLE
Create a component to display information on a specific Cluster

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/pathways#52]
### Expected Behaviour

When we fetch data on a Route we receive a large object that contains several Clusters. For each Cluster we will need to display a card with some information.

The new component should be called `ClusterCard.tsx` and needs to display the following:

- name
- description
- technicalLevelName

### Current Behaviour

We don't show the user any information on the Route they've searched right now.

### Any other notes

This is an example of a cluster that I took from the API:

```json          
  {
              "object": "Cluster",
              "id": 96,
              "name": "Human resources administrator",
              "description": "Provision of largely transactional human resource services e.g. recruitment, HR administration, rewards and recognition, training and development, etc",
              "technicalLevel": 1,
              "technicalLevelName": "Technical",
              "occupations": [
                {
                  "object": "Occupation",
                  "stdCode": "OCC0239",
                  "name": "HR support",
                  "status": 1,
                  "statusName": "Approved occupation",
                  "level": 3,
                  "versionNo": "1.1",
                  "statusLastUpdated": "2017-08-25"
                },
                {
                  "object": "Occupation",
                  "stdCode": "OCC0562",
                  "name": "Learning and development practitioner",
                  "status": 1,
                  "statusName": "Approved occupation",
                  "level": 3,
                  "versionNo": "1.0",
                  "statusLastUpdated": "2018-08-08"
                },
                {
                  "object": "Occupation",
                  "stdCode": "OCC0320",
                  "name": "Recruitment consultant",
                  "status": 1,
                  "statusName": "Approved occupation",
                  "level": 3,
                  "versionNo": "1.0",
                  "statusLastUpdated": "2017-12-20"
                },
                {
                  "object": "Occupation",
                  "stdCode": "OCC0321",
                  "name": "Recruitment resourcer",
                  "status": 1,
                  "statusName": "Approved occupation",
                  "level": 2,
                  "versionNo": "1.0",
                  "statusLastUpdated": "2017-12-20"
                }
              ],
              "sequence": 0
  ```

Use it to develop the component.

**Comment by PL1106** [comment]
To do this task you need a new component called ClusterCard. It will handle displaying specific details like the name, description, and technicalLevelName for each cluster within the fetched route data. In the App.js, then include ClusterCard and loop through routeDetails.clusters to render individual cards for each cluster. This checks that each cluster's key information is presented, and communicates route data to users.

**Comment by PL1106** [comment]
I made some progress however I'm still not getting what I want would you mind giving me some feedback so that i can work on it after lunch

**Comment by camelPhonso** [comment]
Your component needs to only receive the three values we described in the issue as it's props.

Move any fetch calls outside of the component and make sure you pass down the information it needs to render.

To start with, create a stories file and make sure it renders your component - do this by copying the example object I gave you in the issue description and saving it as a variable in the stories file. Then ['destructure'](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) the three values you need and pass them to your component.

Once that is working fine you can then worry about making the actual fetch call in the page and passing down the values you've gathered.
