### ISSUE TITLE
Create `HierarchyMap.jsx` component

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/pathways#67]
### Expected Behaviour

Users will want to expand on the information given in any OccupationCard and be able to learn more about each occupation.

For that we will need a new component that displays the extended details of the occupation objects returned from the API

### Current Behaviour

There is nowhere to read information like the overview of an occupation for example

### Any other notes

The `HierarchyMap.jsx` is the first [container component](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) you'll be dealing with. For now don't worry about displaying the `OccupationCard`s inside it. Just create the larger component.

It needs to look like this:
![Image](https://github.com/user-attachments/assets/800f11ba-1dbb-4b3d-9e15-04fb412594af)

The "Technical", "Higher Technical" and "Professional" headers are static so it only needs to received a prop called `routeName` for now, which in the case of this example displays "Digital".

We will need to work on displaying the `OccupationCard`s inside it after this is done

**Comment by PL1106** [comment]
There are a few errors which aren't letting me run the storybook but i will try get them fixed before lunch.
