### ISSUE TITLE
Create `Header.jsx` component

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/pathways#68]
### Expected Behaviour

The page needs a header where our search bar will live as well as some branding for gatsby.

### Current Behaviour

There's no header at all. Everything is displayed in the body of `App.jsx`

### Any other notes

The figma example of this component will be added here soon. Do not start on this issue before that.

**Comment by PL1106** [comment]
To do this task I will make a header.jsx file which is a component that will create a header for the application, featuring a title and a search bar It will use styles to look good .
